### ISSUE TITLE
看起来没有处理签名参数和时间戳？好像很容易失效啊

### ISSUE THREAD

**Issue by icesunx** [gisShield/douyin#1]

**Comment by x-pyrrhus** [comment]
这个现在是不是失效了

**Comment by icesunx** [comment]
@Just-Like 
https://github.com/AppSign/douyin
暂时先用这个的服务来签名参数吧，试了可以

**Comment by x-pyrrhus** [comment]
> @Just-Like
> https://github.com/AppSign/douyin
> 暂时先用这个的服务来签名参数吧，试了可以

嗯 我也发现这个项目了  不过算法 没有公开 不敢大肆引用

**Comment by icesunx** [comment]
@Just-Like 算法都是拿来卖的，估计没人公开……我有收到可用的旧版的算法，问他们都是卖几千（新/旧）呵呵

**Comment by x-pyrrhus** [comment]
> @Just-Like 算法都是拿来卖的，估计没人公开……我有收到可用的旧版的算法，问他们都是卖几千（新/旧）呵呵

了解了
